# Generated by Django 5.2 on 2025-04-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commetn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commetn',
            new_name='Comment',
        ),
    ]
